name: todo
description: "A basic ToDo app with basic features like creating and editing tasks."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

